### ISSUE TITLE
All maps fail to upload - Length exceeded allowed maximum (858665762)

### ISSUE THREAD

**Issue by JABirchall** [BigBang1112/gbx-net#134]
Full log:

```
Debug DrRace 01.Map.Gbx -> File size: 474126 bytes
Debug DrRace 01.Map.Gbx -> Last modified: 11/26/2024 03:40:02
Info DrRace 01.Map.Gbx -> Opening the file stream...
Info DrRace 01.Map.Gbx -> Verifying that the stream is a Gbx stream...
Info DrRace 01.Map.Gbx -> Calculating SHA256...
Debug DrRace 01.Map.Gbx -> SHA256: e4d5c2a9f81e745722e70118cff39797c6ff7cab70c192d63e9afeee4128274c
Info DrRace 01.Map.Gbx -> File is unique. Importing the Gbx...
Info DrRace 01.Map.Gbx -> GBX.NET -> Gbx Parse (IMPLICIT)
Debug DrRace 01.Map.Gbx -> GBX.NET -> File path: (null)
Debug DrRace 01.Map.Gbx -> GBX.NET -> Parsing header... (IMPLICIT, basic, UserData, number of nodes)
Debug DrRace 01.Map.Gbx -> GBX.NET -> Header -> Basic: 6 Binary Uncompressed Compressed R
Debug DrRace 01.Map.Gbx -> GBX.NET -> Header -> Class ID: 0x03043000 (CGameCtnChallenge)
Info DrRace 01.Map.Gbx -> GBX.NET -> Header -> Known class!
Debug DrRace 01.Map.Gbx -> GBX.NET -> Header -> UserData: 107543 bytes (read skipped - OpenPlanetHookExtractMode)
Debug DrRace 01.Map.Gbx -> GBX.NET -> Header -> Number of nodes: 6
Debug DrRace 01.Map.Gbx -> GBX.NET -> Number of external nodes: 50606082
Debug DrRace 01.Map.Gbx -> GBX.NET -> RefTable -> Ancestor level: 57
Error DrRace 01.Map.Gbx -> Import has thrown LengthLimitException -> Length exceeded allowed maximum (858665762).

    GBX.NET.Exceptions.LengthLimitException: Length exceeded allowed maximum (858665762).
    at GBX.NET.Serialization.GbxReader.ReadString(Int32 length)
    at GBX.NET.Serialization.GbxReader.ReadString()
    at GBX.NET.Serialization.GbxRefTableReader.ReadChildren(Dir currentDir)+MoveNext()
    at GBX.NET.Serialization.GbxRefTableReader.ReadChildren(Dir currentDir)+MoveNext()
    at GBX.NET.Serialization.GbxRefTableReader.ReadChildren(Dir currentDir)+MoveNext()
    at System.Collections.Generic.List`1[[GBX.NET.Serialization.GbxRefTableReader.Dir, GBX.NET, Version=2.0.9.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 )
    at System.Linq.Enumerable.ToList[Dir](IEnumerable`1 )
    at GBX.NET.Serialization.GbxRefTableReader.Parse()
    at GBX.NET.Components.GbxRefTable.Parse(GbxReader reader, GbxHeader header, String fileSystemPath)
    at GBX.NET.Gbx.ParseAsync(Stream stream, GbxReadSettings settings, CancellationToken cancellationToken)
    at GbxExplorerOld.Client.Services.GbxService.ImportGbxAsync(IBrowserFile file, Func`2 asyncEvent, CancellationToken cancellationToken)
```

This happens with every map, even previous maps which has uploaded fine before.

**Comment by BigBang1112** [comment]
You accidentally left `OpenPlanetHookExtractMode` setting on. It exists for easier management of OP-extracted files, but it cannot recognize this binary state, so you have to enable and disable it per usage.

**Comment by JABirchall** [comment]
Ahh, you right.
I dont remeber enabling that, but disabling it worked.
