### ISSUE TITLE
Unknown node 0x02500200 when parsing recent .Block.Gbx files

### ISSUE THREAD

**Issue by ErwanFagnou** [BigBang1112/gbx-net#78]
Hi!

# Description

I am working on a project where I parse a lot of custom blocks from TM2020. While most of them work perfectly, I sometimes get an error:
`Wrong chunk format or unskippable chunk: 0x02500200 (unknown class)`

I believe this happens for recently made blocks: when I create a custom block from a vanilla block in the TM map editor (for instance the one linked below), I get the error when parsing it. I don't have the error for older block files (downloaded from item exchange).

# Environment
I am on Windows 11, using GBX.NET v1.2.2 (installed using NuGet) with Visual Studio.
All files are from TrackMania2020.

# Reproducibility
Try to open this file: https://file.io/I3YmM1fSpdat
With the code:

```cs
using GBX.NET;
GameBox.ParseNode("./GateCheckpoint.Block.Gbx");
```

# Error log
Log from the website https://gbxexplorer.net/ because it contains more information.

```
INFO: Ready to import 1 file...
DEBUG: GateCheckpoint.Block.Gbx -> File size: 568 bytes
DEBUG: GateCheckpoint.Block.Gbx -> Last modified: 11/19/2023 00:55:21
INFO: GateCheckpoint.Block.Gbx -> Opening the file stream...
INFO: GateCheckpoint.Block.Gbx -> Verifying that the stream is a Gbx stream...
INFO: GateCheckpoint.Block.Gbx -> Calculating SHA256...
DEBUG: GateCheckpoint.Block.Gbx -> SHA256: bb8ae589ca924400321f94801bdb5e7c29685ddf265f6e94a2ceb42780aa4f3b
INFO: GateCheckpoint.Block.Gbx -> File is unique. Importing the Gbx...
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> GBX magic found
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> Version: 6
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> Format: Byte
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> Ref. table compression: Uncompressed
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> Body compression: Compressed
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> Unknown byte: R
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> Class ID: 0x2E002000
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> User data size: 0.13574219 kB
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> Number of nodes: 4
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> Header complete
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> Header chunks:
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> - 0x2E001003 | 87 B
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> - 0x2E001006 | 8 B
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> - 0x2E002000 | 4 B
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> - 0x2E002001 | 4 B
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> Reading the body...
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E001009 (0.5471957%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E00100B (5.1983585%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E00100C (10.9439125%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E00100D (13.132694%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E001010 (16.689466%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E001011 (19.425444%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E001012 (22.298222%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E002008 (25.0342%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E002009 (29.95896%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E00200C (31.600548%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E002012 (32.69494%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E002015 (37.072502%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E002019 (38.166897%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> CGameBlockItem -> 0x2E025000 (43.091656%)
DEBUG: GateCheckpoint.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> CGameBlockItem -> 0x02500200 (49.384407%)
ERROR: GateCheckpoint.Block.Gbx -> Import has thrown ChunkParseException -> Wrong chunk format or unskippable chunk: 0x02500200 (unknown class)
Previous chunk: 0x2E025000 (GameData::CGameBlockItem)

GBX.NET.Exceptions.ChunkParseException: Wrong chunk format or unskippable chunk: 0x02500200 (unknown class)
Previous chunk: 0x2E025000 (GameData::CGameBlockItem)
   at GBX.NET.Node.IterateChunks(Node node, GameBoxReader r, IProgress`1 progress, Nullable`1& previousChunkId, Boolean ignoreZeroIdChunk)
   at GBX.NET.Node.ReadChunkData(GameBoxReader r, IProgress`1 progress, Boolean ignoreZeroIdChunk)
   at GBX.NET.Node.Parse(Node node, GameBoxReader r, IProgress`1 progress, Boolean ignoreZeroIdChunk)
   at GBX.NET.Node.Parse(GameBoxReader r, Nullable`1 classId, IProgress`1 progress, Boolean ignoreZeroIdChunk)
   at GBX.NET.GameBoxReader.ReadNodeRef(File& nodeRefFile)
   at GBX.NET.GameBoxReader.ReadNodeRef[CMwNod]()
   at GBX.NET.GameBoxReaderWriter.NodeRef[CMwNod](CMwNod variable)
   at GBX.NET.GameBoxReaderWriter.NodeRef[CMwNod](CMwNod& variable, Boolean disallowOverride)
   at GBX.NET.Engines.GameData.CGameItemModel.Chunk2E002019.ReadWrite(CGameItemModel n, GameBoxReaderWriter rw)
   at GBX.NET.Chunk`1[[GBX.NET.Engines.GameData.CGameItemModel, GBX.NET, Version=1.2.2.0, Culture=neutral, PublicKeyToken=null]].GBX.NET.IReadableWritableChunk.ReadWrite(Node n, GameBoxReaderWriter rw)
   at GBX.NET.Node.ReadWriteChunkAsync(Node node, IReadableWritableChunk chunk, GameBoxReaderWriter rw, CancellationToken cancellationToken)
   at GBX.NET.Node.ReadUnskippableChunkAsync(Node node, GameBoxReader r, UInt32 chunkId, CancellationToken cancellationToken)
   at GBX.NET.Node.IterateChunksAsync(Node node, GameBoxReader r, Nullable`1 previousChunkId, CancellationToken cancellationToken)
   at GBX.NET.Node.ReadChunkDataAsync(GameBoxReader r, CancellationToken cancellationToken)
   at GBX.NET.Node.ParseAsync(Node node, GameBoxReader r, CancellationToken cancellationToken)
   at GBX.NET.GameBoxBody.ReadMainNodeAsync(Node node, GameBoxReader reader, CancellationToken cancellationToken)
   at GBX.NET.GameBoxBody.ReadMainNodeAsync(Node node, Stream stream, ILogger logger, GameBoxAsyncReadAction asyncAction, GbxState state, CancellationToken cancellationToken)
   at GBX.NET.GameBoxBody.ReadMainNodeAsync(Node node, Byte[] data, ILogger logger, GameBoxAsyncReadAction asyncAction, GbxState state, CancellationToken cancellationToken)
   at GBX.NET.GameBoxBody.ReadMainNodeAsync(Node node, Byte[] data, Int32 uncompressedSize, ILogger logger, GameBoxAsyncReadAction asyncAction, GbxState state, CancellationToken cancellationToken)
   at GBX.NET.GameBoxBody.ReadCompressedAsync(Node node, GameBoxReader reader, GameBoxAsyncReadAction asyncAction, CancellationToken cancellationToken)
   at GBX.NET.GameBoxBody.ReadAsync(Node node, GameBoxHeader header, GameBoxReader reader, Boolean readUncompressedBodyDirectly, GameBoxAsyncReadAction asyncAction, CancellationToken cancellationToken)
   at GBX.NET.GameBox.ParseAsync(Stream stream, Boolean readUncompressedBodyDirectly, ILogger logger, GameBoxAsyncReadAction asyncAction, CancellationToken cancellationToken)
   at GbxExplorer.Client.Services.GbxService.ImportGbxAsync(IBrowserFile file, Func`2 asyncEvent, CancellationToken cancellationToken)

```

**Comment by ErwanFagnou** [comment]
By the way for the blocks that don't give the error, I sometimes get warnings that some nodes are unknown -- but skippable so it's not really an issue, I'm just saying this for the record.

Here is a file that gives the warnings:
And the extract of the logs:
```
[...]
DEBUG: 1-1-1-1-Ice-Light.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> CGameBlockItem -> CPlugCrystal -> 0x09003007 (97.54656%)
DEBUG: 1-1-1-1-Ice-Light.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> CGameBlockItem -> CPlugCrystal -> DONE! (20.8ms)
DEBUG: 1-1-1-1-Ice-Light.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> CGameBlockItem -> 0x2E025001 (98.58414%)
WARN: 1-1-1-1-Ice-Light.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> CGameBlockItem -> 0x2E025001 [unknown] (24 bytes)
DEBUG: 1-1-1-1-Ice-Light.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> CGameBlockItem -> 0x2E025002 (98.71384%)
WARN: 1-1-1-1-Ice-Light.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> CGameBlockItem -> 0x2E025002 [unknown] (8 bytes)
DEBUG: 1-1-1-1-Ice-Light.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> CGameBlockItem -> 0x2E025003 (98.78589%)
WARN: 1-1-1-1-Ice-Light.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> CGameBlockItem -> 0x2E025003 [unknown] (5 bytes)
DEBUG: 1-1-1-1-Ice-Light.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> CGameBlockItem -> DONE! (24.4ms)
DEBUG: 1-1-1-1-Ice-Light.Block.Gbx -> GBX.NET -> CGameItemModel (async) -> 0x2E00201C (98.904785%)
[...]
```

**Comment by BigBang1112** [comment]
Damn, there were some new additions to `CGameBlockItem` `0x2E025000` that I haven't noticed. I even have them decompiled properly. :D

I did some steps to figure this out, [try it here](https://bigbang1112.github.io/gbx-net/). There's a new U01 value on the chunk, which will likely fail if it's different from 0. Send me those that are different from 0.

Warnings are part of undiscovered values that should be just fine to not know for now. `0x001` seems easy but `0x002` looks to be a bit more confusing without a context.

**Comment by ErwanFagnou** [comment]
Great, works like a charm! Thanks a lot for the quick fix.

It seems the U01 value is always 0 for the blocks I loaded (out of 5 blocks: one I made myself today and 4 from an older block set from item exchange).

Do you plan on releasing this fixed version? I'm not quite sure how I can use the dev branch in my project, as I am using NuGet.

**Comment by BigBang1112** [comment]
Could take some weeks to integrate.

**Comment by ErwanFagnou** [comment]
Alright, this is not urgent for me, if it is easy for you to push a 1.3-alpha then that would be nice but otherwise I can wait.

I'm closing this issue, thanks again for your work!

**Comment by BigBang1112** [comment]
Ok nevermind, because of the suspicion of the new content coming up real soon to TM2020, I might have to fix some features with basic gbx objects like maps and replays. So it will come in full form version 1.2.3.
