### ISSUE TITLE
TM2020 snow car update breaks Ghost.Gbx files

### ISSUE THREAD

**Issue by ErwanFagnou** [BigBang1112/gbx-net#79]
Hello again.

As expected, the update broke a few things -- actually, only the ghost (and replay) files. Maps and blocks work perfectly file (with the current dev version).

Here is a ghost that makes the parser throw an exception: https://file.io/qdXOrg0S2SmQ

And the error log from https://bigbang1112.github.io/gbx-net/:
```
INFO: Ready to import 1 file...
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> File size: 38407 bytes
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> Last modified: 11/21/2023 21:57:16
INFO: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> Opening the file stream...
INFO: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> Verifying that the stream is a Gbx stream...
INFO: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> Calculating SHA256...
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> SHA256: b574651dc87e3e9bbf449775ee17e02d44c92ba78a7f1d6e1d591d821a176cf8
INFO: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> File is unique. Importing the Gbx...
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> GBX magic found
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> Version: 6
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> Format: Byte
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> Ref. table compression: Uncompressed
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> Body compression: Compressed
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> Unknown byte: R
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> Class ID: 0x03092000
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> User data size: 0 kB
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> Number of nodes: 2
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> Header complete
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> Reading the body...
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> CGameCtnGhost (async) -> 0x0303F006 (0.010014772%)
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> CGameCtnGhost (async) -> 0x0303F007 (0.08011818%)
DEBUG: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> GBX.NET -> CGameCtnGhost (async) -> 0x03092000 (0.12017726%)
ERROR: 16681ed3-7a48-40b6-979c-502ab442f2ad.Ghost.gbx -> Import has thrown VersionNotSupportedException -> Version 1 is not supported.

GBX.NET.Exceptions.VersionNotSupportedException: Version 1 is not supported.
   at GBX.NET.GameBoxReader.ReadId(Boolean cannotBeCollection)
   at GBX.NET.GameBoxReader.ReadIdent()
   at GBX.NET.GameBoxReaderWriter.Ident(Ident variable)
   at GBX.NET.GameBoxReaderWriter.Ident(Ident& variable)
   at GBX.NET.Engines.Game.CGameCtnGhost.Chunk03092000.ReadWrite(CGameCtnGhost n, GameBoxReaderWriter rw)
   at GBX.NET.Chunk`1[[GBX.NET.Engines.Game.CGameCtnGhost, GBX.NET, Version=1.2.3.0, Culture=neutral, PublicKeyToken=null]].GBX.NET.IReadableWritableChunk.ReadWrite(Node n, GameBoxReaderWriter rw)
   at GBX.NET.Node.CreateKnownSkippableChunk(Node node, UInt32 chunkId, Byte[] chunkData, GameBoxReader reader)
   at GBX.NET.Node.ReadSkippableChunkAsync(Node node, GameBoxReader r, UInt32 chunkId, Boolean reflected, CancellationToken cancellationToken)
   at GBX.NET.Node.IterateChunksAsync(Node node, GameBoxReader r, Nullable`1 previousChunkId, CancellationToken cancellationToken)
   at GBX.NET.Node.ReadChunkDataAsync(GameBoxReader r, CancellationToken cancellationToken)
   at GBX.NET.Node.ParseAsync(Node node, GameBoxReader r, CancellationToken cancellationToken)
   at GBX.NET.GameBoxBody.ReadMainNodeAsync(Node node, GameBoxReader reader, CancellationToken cancellationToken)
   at GBX.NET.GameBoxBody.ReadMainNodeAsync(Node node, Stream stream, ILogger logger, GameBoxAsyncReadAction asyncAction, GbxState state, CancellationToken cancellationToken)
   at GBX.NET.GameBoxBody.ReadMainNodeAsync(Node node, Byte[] data, ILogger logger, GameBoxAsyncReadAction asyncAction, GbxState state, CancellationToken cancellationToken)
   at GBX.NET.GameBoxBody.ReadMainNodeAsync(Node node, Byte[] data, Int32 uncompressedSize, ILogger logger, GameBoxAsyncReadAction asyncAction, GbxState state, CancellationToken cancellationToken)
   at GBX.NET.GameBoxBody.ReadCompressedAsync(Node node, GameBoxReader reader, GameBoxAsyncReadAction asyncAction, CancellationToken cancellationToken)
   at GBX.NET.GameBoxBody.ReadAsync(Node node, GameBoxHeader header, GameBoxReader reader, Boolean readUncompressedBodyDirectly, GameBoxAsyncReadAction asyncAction, CancellationToken cancellationToken)
   at GBX.NET.GameBox.ParseAsync(Stream stream, Boolean readUncompressedBodyDirectly, ILogger logger, GameBoxAsyncReadAction asyncAction, CancellationToken cancellationToken)
   at GbxExplorer.Client.Services.GbxService.ImportGbxAsync(IBrowserFile file, Func`2 asyncEvent, CancellationToken cancellationToken)

INFO: Import completed!
```

For your information, I tried parsing different file types after the update:
- .Map.Gbx : no problem (with some new blocks inside)
- .Block.Gbx: no problem (I just tried exporting a wood road block from the editor, and it loaded nicely)
- .Ghost.Gbx: unsupported version error :/
- .Replay.Gbx: error, but the same as for ghosts, and that's to be expected as it contains a ghost file

**Comment by BigBang1112** [comment]
I'm figuring out the best way to deal about the new update. Decompilation seems to take ages for some reason, so I'm going to try the good old way of guessing the structure. Hopefully before the end of the week I should have an update.

**Comment by BigBang1112** [comment]
I figured out this purely by guessing, I guess I'll go with that and update with it. https://github.com/BigBang1112/gbx-net/commit/445f59746bca28975e06ad0ae0479bdb45fd9e17
